version: '3.9'

services:

  # main build for PHP
  php:
    build:
      dockerfile: ./Dockerfile
    container_name: ${APP_NAME}_php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"

  # Nginx
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - postgres

  # PostGreSQL
  postgres:
    container_name: ${APP_NAME}_postgres
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    depends_on:
      - php 

  # PG admin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - postgres 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 

  
    